version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devquest
      MYSQL_USER: devquest
      MYSQL_PASSWORD: devquest1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
  mysql_data:
    driver: local

#docker-compose up --build



#docker exec -it mysql mysql -u root -p

#docker exec -it mysql mysql -u devquest -p 
#devquest1234

#use devquest;