name: PR Test - GuildApiTest

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew
      
    - name: Run GuildApiTest
      run: |
        cd backend
        ./gradlew test --tests "com.devquest.devquest.acceptance.domain.GuildApiTest" --info
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          backend/build/reports/tests/
          backend/build/test-results/
          
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: GuildApiTest Results
        path: backend/build/test-results/test/*.xml
        reporter: java-junit
